In [1]:
import pandas as pd

# Season-wise Friends viewership data (simplified)
data = {
    "Season": list(range(1, 11)),
    "Number of Episodes": [24, 24, 25, 24, 24, 25, 24, 24, 24, 18],
    "Average Viewers (millions)": [24.3, 29.4, 25.0, 24.7, 23.5, 20.7, 21.6, 24.5, 21.6, 22.8]
}

df = pd.DataFrame(data)
df.to_csv("../data/friends_viewership.csv", index=False)
df

/var/folders/11/1z2rlbps68d_flh4dt29lm100000gq/T/ipykernel_12608/3098613798.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

   Season  Number of Episodes  Average Viewers (millions)
0       1                  24                        24.3
1       2                  24                        29.4
2       3                  25                        25.0
3       4                  24                        24.7
4       5                  24                        23.5
5       6                  25                        20.7
6       7                  24                        21.6
7       8                  24                        24.5
8       9                  24                        21.6
9      10                  18                        22.8